services:
    # Default settings for all services defined in this file
    _defaults:
        autowire: false # Autowiring is disabled, meaning dependencies will not be automatically injected
        autoconfigure: false # Autoconfiguration is disabled, preventing automatic tagging
        public: false  # All services are private by default and can't be accessed directly from outside the container

    # Declare the Transformer service
    Lodel\DataInteroperabilityBundle\Service\Transformer:
        public: true # This service is explicitly made public for access if needed
        arguments:
            $params: '@parameter_bag' # Injects the parameter bag to retrieve parameters from YAML

    # Declare the TransformationProvider service
    Lodel\DataInteroperabilityBundle\Service\TransformationProvider:
        arguments:
            $params: '@parameter_bag' # Injects the ParameterBagInterface for retrieving configuration
    
    # Declare the TeiUploadFormListener service
    Lodel\DataInteroperabilityBundle\EventListener\TeiUploadFormListener:
        arguments:
            $transformer: '@Lodel\DataInteroperabilityBundle\Service\Transformer' # Inject the Transformer service
        tags:
            - { name: 'form.event_subscriber' } # Registers this as a form event subscriber

    # Declare the TeiUploadFormTypeExtension service
    Lodel\DataInteroperabilityBundle\Form\TeiUploadFormTypeExtension:
        arguments:
            $formListener: '@Lodel\DataInteroperabilityBundle\EventListener\TeiUploadFormListener' # Injects the form listener
            $transformationProvider: '@Lodel\DataInteroperabilityBundle\Service\TransformationProvider' # Injects TransformationProvider
        tags:
            - { name: form.type_extension } # Registers this as a form type extension
