name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP 8.1 with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl, pcntl, zip, xsl
          tools: composer, symfony

      - name: Install required system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libxslt-dev libzip-dev libicu-dev zip unzip git default-jre openssh-client

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-

      - name: Install project dependencies
        run: |
         # REMOVE: The following block removes the 'lodel/lodel' repository and package from the project configuration -->
          composer remove lodel/lodel --no-update
          composer config --unset repositories
         # <-- REMOVE: End of block to be removed
          composer install --no-interaction --prefer-dist

      - name: Upload vendor and composer.lock
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: |
            vendor
            composer.lock
