name: Code Quality

on:
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP 8.1 with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: dependencies

      - name: Fix permissions for vendor/bin executables
        run: chmod +x vendor/bin/*

      - name: Run YAML lint
        run: vendor/bin/yaml-lint src tests

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run
            
      - name: Run PHPStan
        run: |
         # REMOVE: The following block adds ignore rules for PHPStan to suppress errors related to missing Lodel classes -->
            sed -i '/^ *ignoreErrors:/a\
             - "#Class Lodel\\\\\\\\.* not found#"\
             - "#Call to method .* on an unknown class Lodel\\\\\\\\.*#"\
             - "#Trying to mock an undefined method .* on class Lodel\\\\\\\\.*#"\
             - "#PHPDoc tag @var .* contains unknown class Lodel\\\\\\\\.*#"\
             - "#Parameter .* has invalid type Lodel\\\\\\\\.*#"\
             - "#Property .* has unknown class Lodel\\\\\\\\.* as its type#"' phpstan.neon.dist
         # <-- REMOVE: End of block to be removed
          vendor/bin/phpstan analyse
